### ISSUE TITLE
pbs doesnt seem to work out of the box with `geotagx-project-template`'s output

### ISSUE THREAD

**Issue by spMohanty** [geotagx/geotagx-project-template#17] opened 2015-06-17 14:45 UTC

**Comment by othieno** [comment] 2015-06-17 15:12
@spMohanty I've been wondering why this is happening too because locally everything works fine (even after reinstalling PyBossa), however when I try to push to the remote server, all hell breaks loose.

I've gotten the same errors when trying to create the app-flickrperson project via `pbs` so we can safely assume the problem isn't in the project-template's output. Have you tried playing with app-flickrperson? You might have a different result than I did.

**Comment by spMohanty** [comment] 2015-06-17 15:21
app-flickerperson works fine !! i just tested !!

Update : Now it doesnot !! Looks like its a bit buggy, and the error messages are so not clear !! And if its always working on localhost, I would say, we can simply just run it everytime direclty from the server !! might be some latency/timeout issue and coupled with bad error messages, makes things worse !

**Comment by othieno** [comment] 2015-06-17 15:29
Aha! Interesting. Could you please paste the error you get when trying to upload a GeoTag-X project?

**Comment by spMohanty** [comment] 2015-06-17 15:44
There you go. and I find the same issue when creating a project on localhost too !! 

``` bash
(env)pb-d-128-141-230-42:app-flickrperson spmohanty$ pbs create_project
Traceback (most recent call last):
  File "/Users/spmohanty/work/geotagx/geotagx-enki/enki/env/bin/pbs", line 9, in <module>
    load_entry_point('pybossa-pbs==1.7.2', 'console_scripts', 'pbs')()
  File "/Users/spmohanty/work/geotagx/geotagx-enki/enki/env/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Users/spmohanty/work/geotagx/geotagx-enki/enki/env/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Users/spmohanty/work/geotagx/geotagx-enki/enki/env/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/spmohanty/work/geotagx/geotagx-enki/enki/env/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/spmohanty/work/geotagx/geotagx-enki/enki/env/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Users/spmohanty/work/geotagx/geotagx-enki/enki/env/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/spmohanty/work/geotagx/geotagx-enki/enki/env/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Users/spmohanty/work/geotagx/geotagx-enki/enki/env/lib/python2.7/site-packages/pbs.py", line 118, in create_project
    res = _create_project(config)
  File "/Users/spmohanty/work/geotagx/geotagx-enki/enki/env/lib/python2.7/site-packages/helpers.py", line 50, in _create_project
    check_api_error(response)
  File "/Users/spmohanty/work/geotagx/geotagx-enki/enki/env/lib/python2.7/site-packages/helpers.py", line 227, in check_api_error
    error=api_response)
pbsexceptions.ProjectNotFound: PyBossa Project not found
```

**Comment by othieno** [comment] 2015-06-17 15:48
Alright, thanks. I'll look into it and get back to you.

**Comment by spMohanty** [comment] 2015-07-19 02:42
Adding the contents of the email to this thread for future reference

```
So the issue with pbs was indeed an issue with the wrong versions of 
dependencies listed in geotagx-project-template repository.

Another interesting thing to note is, the API-KEYs change from time to time
 in the new version of pybossa, so if we see the "Project Not Found" issue, 
it is most probably because the API key has been changed automatically, 
and we need to update it in ~/.pybossa.cfg

I have updated the requirements.txt file for the geotagx-template repository
 with the correct permutation of versions of all the dependencies for which 
everything works smoothly. I also ran a few tests to bootstrap everything,
 and create project > add tasks > update tempaltes on numerous docker images, 
and everything worked flawlessly every single time.
```

**Comment by elliec** [comment] 2015-07-21 09:16
@spMohanty can we close this?

**Closed as completed** 2015-07-21 12:59 UTC
